const PDFDocument = require('pdfkit');

const money = (n, cur) => `${Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${cur || ''}`.trim();
const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

/**
 * Render an invoice to a PDF Buffer.
 * invoice: { invoice_number, client, client_email, date, due_date, currency, items[], total, notes, account_number }
 * company: { name }
 */
function generateInvoicePdf(invoice, company = {}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      const cur = invoice.currency || '';
      const accent = '#2563eb';

      // Header
      doc.fillColor(accent).fontSize(26).font('Helvetica-Bold').text('INVOICE', 50, 50);
      doc.fillColor('#0f172a').fontSize(13).font('Helvetica-Bold')
        .text(company.name || 'Finpilot', 50, 84);
      doc.moveDown(0.2);

      doc.fontSize(10).font('Helvetica').fillColor('#475569');
      doc.text(`Invoice #: ${invoice.invoice_number || ''}`, 350, 56, { align: 'right' });
      doc.text(`Date: ${fmtDate(invoice.date)}`, 350, 72, { align: 'right' });
      if (invoice.due_date) doc.text(`Due: ${fmtDate(invoice.due_date)}`, 350, 88, { align: 'right' });

      // Bill to
      doc.moveTo(50, 120).lineTo(545, 120).strokeColor('#e2e8f0').stroke();
      doc.fillColor('#94a3b8').fontSize(9).font('Helvetica-Bold').text('BILL TO', 50, 134);
      doc.fillColor('#0f172a').fontSize(12).font('Helvetica-Bold').text(invoice.client || '—', 50, 148);
      if (invoice.client_email) doc.fillColor('#475569').fontSize(10).font('Helvetica').text(invoice.client_email, 50, 166);

      // Items table
      let y = 200;
      const cols = { desc: 50, qty: 330, price: 390, total: 470 };
      doc.fillColor('#fff');
      doc.rect(50, y, 495, 22).fill(accent);
      doc.fillColor('#fff').fontSize(9).font('Helvetica-Bold');
      doc.text('DESCRIPTION', cols.desc + 8, y + 7);
      doc.text('QTY', cols.qty, y + 7, { width: 50, align: 'right' });
      doc.text('UNIT PRICE', cols.price - 10, y + 7, { width: 70, align: 'right' });
      doc.text('TOTAL', cols.total, y + 7, { width: 75, align: 'right' });
      y += 22;

      const items = Array.isArray(invoice.items) ? invoice.items : [];
      doc.font('Helvetica').fontSize(10);
      items.forEach((it, i) => {
        const qty = parseFloat(it.qty) || 0;
        const price = parseFloat(it.unit_price) || 0;
        const lineTotal = qty * price;
        if (i % 2 === 1) { doc.rect(50, y, 495, 22).fill('#f8fafc'); }
        doc.fillColor('#1e293b');
        doc.text(it.description || '—', cols.desc + 8, y + 7, { width: 270 });
        doc.text(String(qty), cols.qty, y + 7, { width: 50, align: 'right' });
        doc.text(money(price, cur), cols.price - 10, y + 7, { width: 70, align: 'right' });
        doc.text(money(lineTotal, cur), cols.total, y + 7, { width: 75, align: 'right' });
        y += 22;
      });

      // Total
      doc.moveTo(330, y + 6).lineTo(545, y + 6).strokeColor('#e2e8f0').stroke();
      doc.fillColor('#0f172a').fontSize(13).font('Helvetica-Bold');
      doc.text('Total', cols.price - 10, y + 16, { width: 70, align: 'right' });
      doc.text(money(invoice.total, cur), cols.total, y + 16, { width: 75, align: 'right' });
      y += 50;

      // Account / notes
      if (invoice.account_number) {
        doc.fillColor('#94a3b8').fontSize(9).font('Helvetica-Bold').text('ACCOUNT / IBAN', 50, y);
        doc.fillColor('#1e293b').fontSize(10).font('Helvetica').text(invoice.account_number, 50, y + 14);
        y += 40;
      }
      if (invoice.notes) {
        doc.fillColor('#94a3b8').fontSize(9).font('Helvetica-Bold').text('NOTES', 50, y);
        doc.fillColor('#475569').fontSize(10).font('Helvetica').text(invoice.notes, 50, y + 14, { width: 495 });
      }

      doc.fillColor('#cbd5e1').fontSize(8).font('Helvetica')
        .text('Generated by Finpilot', 50, 790, { align: 'center', width: 495 });

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

module.exports = { generateInvoicePdf };
